### ISSUE TITLE
add continuous build step to CI

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#176]
When the master branch is built, we should emit a new release. 

I'll add a public GCS storage bucket and make the downloads available from micromdm.io somewhere.

**Comment by Beanow** [comment]
Including a docker build along with that #311 would be awesome.

**Comment by williamtheaker** [comment]
Would attaching a build artifact to `CI.yml` suffice? Something like this:
```
- name: 'Upload build artifact'
      uses: actions/upload-artifact@ea3d524381d563437a7d64af63f3d75ca55521c4 # v2.2.3
      with:
        name: micromdm-development-${{ github.sha }}.zip
        if: github.ref == 'refs/heads/main' # Only trigger on the main branch
        path: micromdm-build.zip
```
